### ISSUE TITLE
Use fast-zlib

### ISSUE THREAD

**Issue by Misly16** [ourpalace/ourcord#15]
someone implement fast-zlib
 
cc @matthewthechickenman @alebot-dev

**Comment by matthewthechickenman** [comment]
cba

**Comment by matthewthechickenman** [comment]
wait did I say cba?

Sorry, I meant ### **The boys of the NYPD choir 
Still singing, "Galway Bay"**

**Comment by alebot-dev** [comment]
Ask Matt (no laptop)

**Comment by xhayper** [comment]
[Done](https://github.com/ourcord/ourcord/pull/55)
